[ids]
0001:0001

[main]
capslock = overloadt(control, escape, 200)
rightalt = backspace
chord_timeout = 300
tap_timeout = 300


a = overloadt(meta, a, 200)
s = overloadt(shift, s, 200)
d = overloadt(alt, d, 200)
f = overloadt(control, f, 200)
j = overloadt(control, j, 200)
k = overloadt(alt, k, 200)
l = overloadt(shift, l, 200)
; = overloadt(meta, ;, 200)
z = b
b = v
x = z
c = x
v = c

